### ISSUE TITLE
Docker and https

### ISSUE THREAD

**Issue by janosimas** [navikt/mock-oauth2-server#102]
Hi,
I'm trying to start a docker server with https but I cannot get it to work. I'm getting parser errors from the sample json rpovided in the readme.

This is the command I'm using:
```sh
docker run -p 8080:8080 -h localhost --env JSON_CONFIG='{"httpServer": {"type":"NettyWrapper","ssl":{}}}'  ghcr.io/navikt/mock-oauth2-server/mock-oauth2-server:0.3.2
```

This is the error I'm getting:
```log
Exception in thread "main" com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot deserialize value of type `no.nav.security.mock.oauth2.OAuth2Config$OAuth2HttpServerDeserializer$ServerType` from Object value (token `JsonToken.START_OBJECT`)
 at [Source: (String)"{"httpServer": {"type":"NettyWrapper","ssl":{}}}"; line: 1, column: 16] (through reference chain: no.nav.security.mock.oauth2.OAuth2Config["httpServer"])
        at com.fasterxml.jackson.databind.exc.MismatchedInputException.from(MismatchedInputException.java:59)
        at com.fasterxml.jackson.databind.DeserializationContext.reportInputMismatch(DeserializationContext.java:1601)
        at com.fasterxml.jackson.databind.DeserializationContext.handleUnexpectedToken(DeserializationContext.java:1375)
        at com.fasterxml.jackson.databind.DeserializationContext.handleUnexpectedToken(DeserializationContext.java:1280)
        at com.fasterxml.jackson.databind.DeserializationContext.extractScalarFromObject(DeserializationContext.java:872)
        at com.fasterxml.jackson.databind.deser.std.EnumDeserializer.deserialize(EnumDeserializer.java:199)
        at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:322)
        at com.fasterxml.jackson.databind.ObjectMapper._readValue(ObjectMapper.java:4569)
        at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2823)
        at com.fasterxml.jackson.core.JsonParser.readValueAs(JsonParser.java:2256)
        at no.nav.security.mock.oauth2.OAuth2Config$OAuth2HttpServerDeserializer.deserialize(OAuth2Config.kt:33)
        at no.nav.security.mock.oauth2.OAuth2Config$OAuth2HttpServerDeserializer.deserialize(OAuth2Config.kt:26)
        at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:542)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeWithErrorWrapping(BeanDeserializer.java:565)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:449)
        at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1405)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:362)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:195)
        at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:322)
        at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4593)
        at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3548)
        at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3531)
        at no.nav.security.mock.oauth2.OAuth2Config$Companion.fromJson(OAuth2Config.kt:48)
        at no.nav.security.mock.oauth2.StandaloneConfig.oauth2Config(StandaloneMockOAuth2Server.kt:27)
        at no.nav.security.mock.oauth2.StandaloneMockOAuth2ServerKt.main(StandaloneMockOAuth2Server.kt:48)
        at no.nav.security.mock.oauth2.StandaloneMockOAuth2ServerKt.main(StandaloneMockOAuth2Server.kt)
```

**Comment by fgstewart** [comment]
The latest image is this one:
```
docker pull ghcr.io/navikt/mock-oauth2-server:0.3.5
```
Your command modified with this image:tag starts fine for me:
```
$ docker run -p 8080:8080 -h localhost --env JSON_CONFIG='{"httpServer": {"type":"NettyWrapper","ssl":{}}}'  ghcr.io/navikt/mock-oauth2-server:0.3.5
...
2021-09-28 15:03:20 [main] DEBUG no.nav.security.mock.oauth2.http.OAuth2HttpServer - started server on address=/0.0.0.0:8080 and port=8080
```

**Comment by janosimas** [comment]
It works with the latest image, thanks
