### ISSUE TITLE
Java 17 support

### ISSUE THREAD

**Issue by mrsladek** [navikt/mock-oauth2-server#137]
Running the server with java 17 produces an error 

`java.lang.UnsupportedOperationException: Reflective setAccessible(true) disabled
	at io.netty.util.internal.ReflectionUtil.trySetAccessible(ReflectionUtil.java:31)
	at io.netty.util.internal.PlatformDependent0$4.run(PlatformDependent0.java:253)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:682)
	at io.netty.util.internal.PlatformDependent0.<clinit>(PlatformDependent0.java:247)
	at io.netty.util.internal.PlatformDependent.isAndroid(PlatformDependent.java:294)
	at io.netty.util.internal.PlatformDependent.<clinit>(PlatformDependent.java:88)
	at io.netty.util.AsciiString.<init>(AsciiString.java:223)
	at io.netty.util.AsciiString.<init>(AsciiString.java:210)
	at io.netty.util.AsciiString.cached(AsciiString.java:1401)
	at io.netty.util.AsciiString.<clinit>(AsciiString.java:48)
	at io.netty.handler.codec.http.HttpHeaderNames.<clinit>(HttpHeaderNames.java:31)
	at no.nav.security.mock.oauth2.http.OAuth2HttpResponseKt.json(OAuth2HttpResponse.kt:62)
	at no.nav.security.mock.oauth2.http.OAuth2HttpRequestHandler.handleRequest(OAuth2HttpRequestHandler.kt:72)
	at no.nav.security.mock.oauth2.MockOAuth2Server$router$1.invoke(MockOAuth2Server.kt:53)
	at no.nav.security.mock.oauth2.MockOAuth2Server$router$1.invoke(MockOAuth2Server.kt:52)
	at no.nav.security.mock.oauth2.http.OAuth2HttpRouterKt$routeFromPathAndMethod$1.invoke(OAuth2HttpRouter.kt:61)
	at no.nav.security.mock.oauth2.http.OAuth2HttpRouterKt$routeFromPathAndMethod$1.invoke(OAuth2HttpRouter.kt:53)
	at no.nav.security.mock.oauth2.http.OAuth2HttpRouter.match(OAuth2HttpRouter.kt:27)
	at no.nav.security.mock.oauth2.http.OAuth2HttpRouter.invoke(OAuth2HttpRouter.kt:20)
	at no.nav.security.mock.oauth2.http.OAuth2HttpRouter.invoke(OAuth2HttpRouter.kt:14)
	at no.nav.security.mock.oauth2.http.MockWebServerWrapper$MockWebServerDispatcher.dispatch(OAuth2HttpServer.kt:90)
	at okhttp3.mockwebserver.MockWebServer$SocketHandler.processOneRequest(MockWebServer.kt:600)
	at okhttp3.mockwebserver.MockWebServer$SocketHandler.handle(MockWebServer.kt:551)
	at okhttp3.mockwebserver.MockWebServer$serveConnection$$inlined$execute$1.runOnce(TaskQueue.kt:220)
	at okhttp3.internal.concurrent.TaskRunner.runTask(TaskRunner.kt:116)
	at okhttp3.internal.concurrent.TaskRunner.access$runTask(TaskRunner.kt:42)
	at okhttp3.internal.concurrent.TaskRunner$runnable$1.run(TaskRunner.kt:65)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:853)`

and then 

`java.lang.IllegalAccessException: class io.netty.util.internal.PlatformDependent0$6 cannot access class jdk.internal.misc.Unsafe (in module java.base) because module java.base does not export jdk.internal.misc to unnamed module @9e7c92f3
	at java.base/jdk.internal.reflect.Reflection.newIllegalAccessException(Reflection.java:385)
	at java.base/java.lang.reflect.AccessibleObject.checkAccess(AccessibleObject.java:687)
	at java.base/java.lang.reflect.Method.invoke(Method.java:559)
	at io.netty.util.internal.PlatformDependent0$6.run(PlatformDependent0.java:375)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:682)
	at io.netty.util.internal.PlatformDependent0.<clinit>(PlatformDependent0.java:366)
	at io.netty.util.internal.PlatformDependent.isAndroid(PlatformDependent.java:294)
	at io.netty.util.internal.PlatformDependent.<clinit>(PlatformDependent.java:88)
	at io.netty.util.AsciiString.<init>(AsciiString.java:223)
	at io.netty.util.AsciiString.<init>(AsciiString.java:210)
	at io.netty.util.AsciiString.cached(AsciiString.java:1401)
	at io.netty.util.AsciiString.<clinit>(AsciiString.java:48)
	at io.netty.handler.codec.http.HttpHeaderNames.<clinit>(HttpHeaderNames.java:31)
	at no.nav.security.mock.oauth2.http.OAuth2HttpResponseKt.json(OAuth2HttpResponse.kt:62)
	at no.nav.security.mock.oauth2.http.OAuth2HttpRequestHandler.handleRequest(OAuth2HttpRequestHandler.kt:72)
	at no.nav.security.mock.oauth2.MockOAuth2Server$router$1.invoke(MockOAuth2Server.kt:53)
	at no.nav.security.mock.oauth2.MockOAuth2Server$router$1.invoke(MockOAuth2Server.kt:52)
	at no.nav.security.mock.oauth2.http.OAuth2HttpRouterKt$routeFromPathAndMethod$1.invoke(OAuth2HttpRouter.kt:61)
	at no.nav.security.mock.oauth2.http.OAuth2HttpRouterKt$routeFromPathAndMethod$1.invoke(OAuth2HttpRouter.kt:53)
	at no.nav.security.mock.oauth2.http.OAuth2HttpRouter.match(OAuth2HttpRouter.kt:27)
	at no.nav.security.mock.oauth2.http.OAuth2HttpRouter.invoke(OAuth2HttpRouter.kt:20)
	at no.nav.security.mock.oauth2.http.OAuth2HttpRouter.invoke(OAuth2HttpRouter.kt:14)
	at no.nav.security.mock.oauth2.http.MockWebServerWrapper$MockWebServerDispatcher.dispatch(OAuth2HttpServer.kt:90)
	at okhttp3.mockwebserver.MockWebServer$SocketHandler.processOneRequest(MockWebServer.kt:600)
	at okhttp3.mockwebserver.MockWebServer$SocketHandler.handle(MockWebServer.kt:551)
	at okhttp3.mockwebserver.MockWebServer$serveConnection$$inlined$execute$1.runOnce(TaskQueue.kt:220)
	at okhttp3.internal.concurrent.TaskRunner.runTask(TaskRunner.kt:116)
	at okhttp3.internal.concurrent.TaskRunner.access$runTask(TaskRunner.kt:42)
	at okhttp3.internal.concurrent.TaskRunner$runnable$1.run(TaskRunner.kt:65)`

**Comment by ybelMekk** [comment]
Hello! @mrsladek Did you find a workaround for this?

**Comment by ybelMekk** [comment]
closing this issue, du to no action or response. Can be opened again later-
