### ISSUE TITLE
question: how to set EC256 algorithm in Unit test?

### ISSUE THREAD

**Issue by tbrandirali** [navikt/mock-oauth2-server#396]
I'm implementing unit tests using the mock server API (not the standalone server). I want the server to sign tokens with ES256 instead of the default RS256, but I'm struggling to configure this. I've tried instantiating the KeyProvider manually, like so:
```kotlin
private val server = MockOAuth2Server(
        OAuth2Config(
            tokenProvider = OAuth2TokenProvider(
                keyProvider = KeyProvider(
                    algorithm = JWSAlgorithm.ES256.name
                )
        ))
    )
```
However, this results in a ClassCastException, seemingly because it is fetching the RSA keys and then trying to cast them to ECDSA:
```
java.lang.ClassCastException: class com.nimbusds.jose.jwk.RSAKey cannot be cast to class com.nimbusds.jose.jwk.ECKey(com.nimbusds.jose.jwk.RSAKey and com.nimbusds.jose.jwk.ECKey are in unnamed module of loader 'app')
	at com.nimbusds.jose.jwk.JWK.toECKey(JWK.java:467)
	at no.nav.security.mock.oauth2.token.OAuth2TokenProvider.sign(OAuth2TokenProvider.kt:112)
	at no.nav.security.mock.oauth2.token.OAuth2TokenProvider.accessToken(OAuth2TokenProvider.kt:60)
	at no.nav.security.mock.oauth2.MockOAuth2Server.issueToken(MockOAuth2Server.kt:226)
	at no.nav.security.mock.oauth2.MockOAuth2Server.issueToken(MockOAuth2Server.kt:241)
	at no.nav.security.mock.oauth2.MockOAuth2Server.issueToken$default(MockOAuth2Server.kt:235)
        ...
```
The workaround I'm currently using is to supply my own keys to the provider:
```kotlin
private val server = MockOAuth2Server(
        OAuth2Config(
            tokenProvider = OAuth2TokenProvider(
                keyProvider = KeyProvider(
                    initialKeys = KeyProvider.keysFromFile("./my-own-keys.json"),
                    algorithm = JWSAlgorithm.ES256.name
                )
        ))
    )
```
This works, but it is indeed a workaround. There are ECDSA keys in [the resources](https://github.com/navikt/mock-oauth2-server/blob/1033dd8/src/main/resources/mock-oauth2-server-keys-ec.json), and it seems like the standalone server is able to use them, so how can I use them from unit tests?

A related issue is that the documentation is not clear about how to configure the mock server for unit tests in general. Can it also be configured using a JSON config file, like the standalone version? If so, how?

**Comment by tbrandirali** [comment]
Update; I realized that:
- The `KeyProvider` actually cannot load my personal keys using `keysFromFile()` due to using `Class.getResource()`, it was just failing silently and generating new keys. I had to supply a `List<JWK>` myself instead.
- I can, instead, pass `KeyProvider.keysFromFile("/mock-oauth2-server-keys-ec.json")` for `initialKeys` to use the library ones.

I guess this solves my main issue. I'm still wondering about the JSON config file, but I can achieve my use cases with the API instead.
