### ISSUE TITLE
AES/GCM/NoPadding decryption failed: Tag mismatch! on standalone server

### ISSUE THREAD

**Issue by rafonsecad** [navikt/mock-oauth2-server#444]
Hi, since version 0.5.7, generating a token from the debugger page causes a `AES/GCM/NoPadding decryption failed: Tag mismatch!`

## Replication

Start mock-oauth2-server as standalone and go to the [debugger page](http://localhost:8080/issuer1/debugger), then click on **GET A TOKEN** button

![image](https://user-images.githubusercontent.com/17520030/223467274-daf4e6a0-8256-4239-ad1f-cc9d7cbce574.png)

Although after clicking the button the page goes to Mock OAuth2 Server Sign-in as normally does, at the terminal we can see an exception is thrown

```
2023-03-07 10:15:34 [nioEventLoopGroup-3-3] ERROR no.nav.security.mock.oauth2.debugger.SessionManager - received exception when decrypting cookie
com.nimbusds.jose.JOSEException: AES/GCM/NoPadding decryption failed: Tag mismatch!
	at com.nimbusds.jose.crypto.impl.AESGCM.decrypt(AESGCM.java:301)
	at com.nimbusds.jose.crypto.impl.ContentCryptoProvider.decrypt(ContentCryptoProvider.java:289)
	at com.nimbusds.jose.crypto.DirectDecrypter.decrypt(DirectDecrypter.java:272)
	at com.nimbusds.jose.JWEObject.decrypt(JWEObject.java:420)
	at no.nav.security.mock.oauth2.debugger.SessionManager$Session.decrypt(SessionManager.kt:51)
	at no.nav.security.mock.oauth2.debugger.SessionManager$Session.getSessionCookie(SessionManager.kt:56)
	at no.nav.security.mock.oauth2.debugger.SessionManager$Session.<init>(SessionManager.kt:30)
	at no.nav.security.mock.oauth2.debugger.SessionManager.session(SessionManager.kt:24)
	at no.nav.security.mock.oauth2.debugger.DebuggerRequestHandlerKt$debuggerForm$1$2.invoke(DebuggerRequestHandler.kt:69)
	at no.nav.security.mock.oauth2.debugger.DebuggerRequestHandlerKt$debuggerForm$1$2.invoke(DebuggerRequestHandler.kt:60)
	at no.nav.security.mock.oauth2.http.OAuth2HttpRouterKt$routeFromPathAndMethod$1.invoke(OAuth2HttpRouter.kt:161)
	at no.nav.security.mock.oauth2.http.OAuth2HttpRouterKt$routeFromPathAndMethod$1.invoke(OAuth2HttpRouter.kt:156)
	at no.nav.security.mock.oauth2.http.PathRouter.invokeWith(OAuth2HttpRouter.kt:117)
	at no.nav.security.mock.oauth2.http.PathRouter.invoke(OAuth2HttpRouter.kt:96)
	at no.nav.security.mock.oauth2.http.PathRouter.invoke(OAuth2HttpRouter.kt:86)
	at no.nav.security.mock.oauth2.debugger.DebuggerRequestHandler.invoke(DebuggerRequestHandler.kt)
	at no.nav.security.mock.oauth2.debugger.DebuggerRequestHandler.invoke(DebuggerRequestHandler.kt:27)
	at no.nav.security.mock.oauth2.http.PathRouter.invokeWith(OAuth2HttpRouter.kt:111)
	at no.nav.security.mock.oauth2.http.PathRouter.invoke(OAuth2HttpRouter.kt:96)
	at no.nav.security.mock.oauth2.http.PathRouter.invoke(OAuth2HttpRouter.kt:86)
	at no.nav.security.mock.oauth2.http.PathRouter.invokeWith(OAuth2HttpRouter.kt:117)
	at no.nav.security.mock.oauth2.http.PathRouter.invoke(OAuth2HttpRouter.kt:96)
	at no.nav.security.mock.oauth2.http.PathRouter.invoke(OAuth2HttpRouter.kt:86)
	at no.nav.security.mock.oauth2.http.NettyWrapper$RouterChannelHandler.channelRead0(OAuth2HttpServer.kt:170)
	at no.nav.security.mock.oauth2.http.NettyWrapper$RouterChannelHandler.channelRead0(OAuth2HttpServer.kt:164)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:93)
	at io.netty.handler.codec.http.HttpServerKeepAliveHandler.channelRead(HttpServerKeepAliveHandler.java:64)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:318)
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: javax.crypto.AEADBadTagException: Tag mismatch!
```

the token generated at the debugger won't work against the server.

**Comment by ybelMekk** [comment]
Hi.

Tanks for opening this issue!

We are going to dig in to this, @tommytroen do you have any clue?

**Comment by rafonsecad** [comment]
hey @tommytroen , yes I have and it works now! Thanks for your patience and also thanks for this amazing project.
