### ISSUE TITLE
Running the standalone Mockserver as a Java exec in Maven is causing a runtime failure

### ISSUE THREAD

**Issue by puneetbabbar26** [navikt/mock-oauth2-server#48]
Hi,

I am using the version `0.3.3` of the `mock-oauth2-server` plugin

I am trying to run the mock-oauth2-server as a standalone process by wrapping it up with `exec-maven-plugin`

This is what the section of the pom looks like 
```xml
           <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>exec-maven-plugin</artifactId>
                <version>3.0.0</version>
                <executions>
                    <execution>
                        <phase>pre-integration-test</phase>
                        <goals>
                            <goal>exec</goal>
                        </goals>
                        <configuration>
                            <executable>java</executable>
                            <classpathScope>test</classpathScope>
                            <async>true</async>
                            <arguments>
                                <argument>-classpath</argument>
                                <classpath/>
                                <argument>no.nav.security.mock.oauth2.StandaloneMockOAuth2ServerKt</argument>
                            </arguments>
                            <environmentVariables>
                                <SERVER_PORT>8989</SERVER_PORT>
                                <JSON_CONFIG_PATH>${target.conf.dir}/${mock-oauth2-config-file}</JSON_CONFIG_PATH>
                            </environmentVariables>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
```

When the server starts up, and the `http://localhost:8989/default/.well-known/openid-configuration` is hit, it fails with the following error

```
10:57:34.976 [nioEventLoopGroup-3-1] WARN  io.netty.channel.DefaultChannelPipeline - An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
java.lang.NoSuchFieldError: Companion
	at no.nav.security.mock.oauth2.http.NettyWrapper$RouterChannelHandler.toOkHttpHeaders(OAuth2HttpServer.kt:195) ~[mock-oauth2-server-0.3.3.jar:?]
	at no.nav.security.mock.oauth2.http.NettyWrapper$RouterChannelHandler.asOAuth2HttpRequest(OAuth2HttpServer.kt:171) ~[mock-oauth2-server-0.3.3.jar:?]
	at no.nav.security.mock.oauth2.http.NettyWrapper$RouterChannelHandler.channelRead0(OAuth2HttpServer.kt:153) ~[mock-oauth2-server-0.3.3.jar:?]
	at no.nav.security.mock.oauth2.http.NettyWrapper$RouterChannelHandler.channelRead0(OAuth2HttpServer.kt:147) ~[mock-oauth2-server-0.3.3.jar:?]
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99) ~[netty-transport-4.1.63.Final.jar:4.1.63.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.63.Final.jar:4.1.63.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.63.Final.jar:4.1.63.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-transport-4.1.63.Final.jar:4.1.63.Final]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) [netty-codec-4.1.63.Final.jar:4.1.63.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.63.Final.jar:4.1.63.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.63.Final.jar:4.1.63.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-transport-4.1.63.Final.jar:4.1.63.Final]
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:93) [netty-transport-4.1.63.Final.jar:4.1.63.Final]
	at io.netty.handler.codec.http.HttpServerKeepAliveHandler.channelRead(HttpServerKeepAliveHandler.java:64) [netty-codec-http-4.1.63.Final.jar:4.1.63.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.63.Final.jar:4.1.63.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.63.Final.jar:4.1.63.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-transport-4.1.63.Final.jar:4.1.63.Final]
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436) [netty-transport-4.1.63.Final.jar:4.1.63.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324) [netty-codec-4.1.63.Final.jar:4.1.63.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296) [netty-codec-4.1.63.Final.jar:4.1.63.Final]
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251) [netty-transport-4.1.63.Final.jar:4.1.63.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.63.Final.jar:4.1.63.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.63.Final.jar:4.1.63.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-transport-4.1.63.Final.jar:4.1.63.Final]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) [netty-transport-4.1.63.Final.jar:4.1.63.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.63.Final.jar:4.1.63.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.63.Final.jar:4.1.63.Final]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) [netty-transport-4.1.63.Final.jar:4.1.63.Final]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166) [netty-transport-4.1.63.Final.jar:4.1.63.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:719) [netty-transport-4.1.63.Final.jar:4.1.63.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655) [netty-transport-4.1.63.Final.jar:4.1.63.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581) [netty-transport-4.1.63.Final.jar:4.1.63.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493) [netty-transport-4.1.63.Final.jar:4.1.63.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) [netty-common-4.1.63.Final.jar:4.1.63.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-common-4.1.63.Final.jar:4.1.63.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-common-4.1.63.Final.jar:4.1.63.Final]
	at java.lang.Thread.run(Thread.java:834) [?:?]
```

Any tips on a possible solution to this issue?

**Comment by tommytroen** [comment]
@puneetbabbar26 This is most likely due to conflicting dependency versions. Can you post your pom.xml or create a sample project with the same dependencies and post the link here?

**Comment by puneetbabbar26** [comment]
Hey @tommytroen 

I tried a Java command line with the entire classpath as well (as derived from pom) to replicate the issue.

here it is 

```
java -classpath ~/.m2/repository/net/minidev/json-smart/2.3/json-smart-2.3.jar:~.m2/repository/com/nimbusds/nimbus-jose-jwt/8.20.2/nimbus-jose-jwt-8.20.2.jar:~.m2/repository/com/fasterxml/jackson/core/jackson-core/2.11.4/jackson-core-2.11.4.jar:~.m2/repository/com/fasterxml/jackson/core/jackson-databind/2.11.4/jackson-databind-2.11.4.jar:~.m2/repository/com/fasterxml/jackson/core/jackson-annotations/2.11.4/jackson-annotations-2.11.4.jar:~.m2/repository/org/slf4j/slf4j-api/1.7.30/slf4j-api-1.7.30.jar:~.m2/repository/org/jetbrains/kotlin/kotlin-reflect/1.4.32/kotlin-reflect-1.4.32.jar:~.m2/repository/no/nav/security/mock-oauth2-server/0.3.3/mock-oauth2-server-0.3.3.jar:~.m2/repository/com/squareup/okhttp3/mockwebserver/3.14.9/mockwebserver-3.14.9.jar:~.m2/repository/com/squareup/okhttp3/okhttp/3.14.9/okhttp-3.14.9.jar:~.m2/repository/com/nimbusds/oauth2-oidc-sdk/8.36.1/oauth2-oidc-sdk-8.36.1.jar:~.m2/repository/com/nimbusds/lang-tag/1.4.4/lang-tag-1.4.4.jar:~.m2/repository/org/jetbrains/kotlin/kotlin-stdlib/1.4.32/kotlin-stdlib-1.4.32.jar:~.m2/repository/ch/qos/logback/logback-classic/1.2.3/logback-classic-1.2.3.jar:~.m2/repository/ch/qos/logback/logback-core/1.2.3/logback-core-1.2.3.jar:~.m2/repository/io/netty/netty-all/4.1.63.Final/netty-all-4.1.63.Final.jar:~.m2/repository/io/github/microutils/kotlin-logging-jvm/2.0.6/kotlin-logging-jvm-2.0.6.jar:~.m2/repository/com/fasterxml/jackson/module/jackson-module-kotlin/2.11.4/jackson-module-kotlin-2.11.4.jar:~.m2/repository/org/freemarker/freemarker/2.3.31/freemarker-2.3.31.jar no.nav.security.mock.oauth2.StandaloneMockOAuth2ServerKt
```

**Comment by tommytroen** [comment]
@puneetbabbar26 it looks like you have got the wrong versions of the `okhttp3` libs - they should be on at least `4.9.1`, but in your output they are on `3.14.9`:

com/squareup/okhttp3/mockwebserver/3.14.9/mockwebserver-3.14.9.jar
com/squareup/okhttp3/okhttp/3.14.9/okhttp-3.14.9.jar

Are you using Spring Boot in your app? I know some users have had some issues with Spring managed versions on `okhttp3`. If you are using Spring you can try to set the property `okhttp3.version` in your pom.xml.

**Comment by puneetbabbar26** [comment]
Thanks @tommytroen I was able to get it to run after spending a lot of time trying to fix the dependencies. 
**Suggestion** - For standalone can you provide a FAT JAR that has all the dependencies that are needed to run the mock-oauth2-server with ease?

Also, I have struggled badly to get the mock server to behave correctly with the expectations and correct tokens. I have used the following file to add 5 different users.

```json
{
    "interactiveLogin": false,
    "httpServer": "NettyWrapper",
    "tokenCallbacks": [
        {
            "issuerId": "default",
            "tokenExpiry": 3600,
            "requestMappings": [
                {
                    "requestParam": "testparam1",
                    "match": "testuser1",
                    "claims": {
                        "userid": "testuser1"
                    }
                }
            ]
        },
        {
            "issuerId": "default",
            "tokenExpiry": 3600,
            "requestMappings": [
                {
                    "requestParam": "testparam2",
                    "match": "testuser2",
                    "claims": {
                        "userid": "testuser2"
                    }
                }
            ]
        },
        {
            "issuerId": "default",
            "tokenExpiry": 3600,
            "requestMappings": [
                {
                    "requestParam": "posuser1",
                    "match": "posuser1",
                    "claims": {
                        "userid": "posuser1"
                    }
                }
            ]
        },
        {
            "issuerId": "default",
            "tokenExpiry": 3600,
            "requestMappings": [
                {
                    "requestParam": "posmanager1",
                    "match": "posmanager1",
                    "claims": {
                        "userid": "posmanager1"
                    }
                }
            ]
        },
        {
            "issuerId": "default",
            "tokenExpiry": 3600,
            "requestMappings": [
                {
                    "requestParam": "testparam3",
                    "match": "testuser3",
                    "claims": {
                        "userid": "testuser3"
                    }
                }
            ]
        }
    ]
}

```

The server would only retain 1 match (randomly) and send the custom claim in token and would not send the custom claim in the token for others.

This is very frustrating to use, you should spruce up the documentation.

I am giving up now, will see in the next few months if the developer experience has improved

**Comment by tommytroen** [comment]
Sorry to hear that you feel its frustrating to use, it can be hard to predict use-cases and how the server is used by different users. We will have a look at the documentation. If you have any specific issues please feel free to open separate issues with details for this. In regards to the FAT jar use case we feel this is covered by the docker version. Closing this issue now.
