### ISSUE TITLE
Exception in thread "MockWebServer" java.lang.NoSuchMethodError: 'okio.Buffer okio.Buffer.copy()'

### ISSUE THREAD

**Issue by kokorin** [navikt/mock-oauth2-server#50]
Hello, thank you for the project.

I want to use it in my project, but unfortunately there is dependency conflict in runtime if `spring-boot-starter-oauth2-client` is used.

Whole stacktrace:

```
Exception in thread "MockWebServer" java.lang.NoSuchMethodError: 'okio.Buffer okio.Buffer.copy()'
	at no.nav.security.mock.oauth2.extensions.RecordedRequestExtensionsKt.asOAuth2HttpRequest(RecordedRequestExtensions.kt:7)
	at no.nav.security.mock.oauth2.http.MockWebServerWrapper$MockWebServerDispatcher.dispatch(OAuth2HttpServer.kt:90)
	at okhttp3.mockwebserver.MockWebServer$4.processOneRequest(MockWebServer.java:573)
	at okhttp3.mockwebserver.MockWebServer$4.processConnection(MockWebServer.java:531)
	at okhttp3.mockwebserver.MockWebServer$4.execute(MockWebServer.java:456)
	at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

Here is the sample project, which reproduces the error: [demo.zip](https://github.com/navikt/mock-oauth2-server/files/6806188/demo.zip)

If `spring-boot-starter-oauth2-client` dependency is commented, MockOAuthServer starts without issues. 

Probably as a workaround one should specify explicit `okio` dependency, I will check this and update this issue.

**UPD**
The following 2 explicit dependencies fix the issue:
```xml
<dependency>
	<groupId>com.squareup.okhttp3</groupId>
	<artifactId>mockwebserver</artifactId>
	<version>4.9.1</version>
	<scope>test</scope>
</dependency>
<dependency>
	<groupId>com.squareup.okhttp3</groupId>
	<artifactId>okhttp</artifactId>
	<version>4.9.1</version>
</dependency>
```

**Comment by ybelMekk** [comment]
More a spring thing. Could be solved as suggested over ☝🏾
