### ISSUE TITLE
Implicit flow not supported

### ISSUE THREAD

**Issue by geld0r** [navikt/mock-oauth2-server#52]
I am trying to use the standalone version provided via docker-compose (exposed on port 8082) and have pointed my locally running app against the mock-server. The app uses an implicit flow triggered by SwaggerUI and produces the following request:

Request:
http://localhost:8082/cola/authorize?response_type=token&client_id=myapp&redirect_uri=http%3A%2F%2Flocalhost%3A8081%2Fswagger-ui%2Foauth2-redirect.html&scope=openid&state=VGh1IEp1bCAxNSAyMDIxIDEyOjExOjM1IEdNVCswMjAwIChDZW50cmFsIEV1cm9wZWFuIFN1bW1lciBUaW1lKQ%3D%3D&realm=myrealm&nonce=dummy

However this fails with the following response:
`{
  "error_description" : "unsupported response type: unsupported response_type parameter: the openid connect response type cannot have token as the only value",
  "error" : "unsupported_response_type"
}`

From the mock-server logs I additionally have this:
`
2021-07-15 10:14:23 [nioEventLoopGroup-3-5] ERROR no.nav.security.mock.oauth2.http.OAuth2HttpRequestHandler - received exception when handling request.
com.nimbusds.oauth2.sdk.ParseException: Unsupported response_type parameter: The OpenID Connect response type cannot have token as the only value
        at com.nimbusds.openid.connect.sdk.AuthenticationRequest.parse(AuthenticationRequest.java:1712)
        at com.nimbusds.openid.connect.sdk.AuthenticationRequest.parse(AuthenticationRequest.java:1975)
        at no.nav.security.mock.oauth2.http.OAuth2HttpRequest.asAuthenticationRequest(OAuth2HttpRequest.kt:76)
        at no.nav.security.mock.oauth2.http.OAuth2HttpRequestHandler.handleAuthenticationRequest(OAuth2HttpRequestHandler.kt:104)
        at no.nav.security.mock.oauth2.http.OAuth2HttpRequestHandler.handleRequest(OAuth2HttpRequestHandler.kt:70)
        at no.nav.security.mock.oauth2.MockOAuth2Server$router$1.invoke(MockOAuth2Server.kt:52)
        at no.nav.security.mock.oauth2.MockOAuth2Server$router$1.invoke(MockOAuth2Server.kt:41)
        at no.nav.security.mock.oauth2.http.OAuth2HttpRouterKt$routeFromPathAndMethod$1.invoke(OAuth2HttpRouter.kt:58)
        at no.nav.security.mock.oauth2.http.OAuth2HttpRouterKt$routeFromPathAndMethod$1.invoke(OAuth2HttpRouter.kt:50)
        at no.nav.security.mock.oauth2.http.OAuth2HttpRouter.match(OAuth2HttpRouter.kt:27)
        at no.nav.security.mock.oauth2.http.OAuth2HttpRouter.invoke(OAuth2HttpRouter.kt:20)
        at no.nav.security.mock.oauth2.http.OAuth2HttpRouter.invoke(OAuth2HttpRouter.kt:14)
        at no.nav.security.mock.oauth2.http.NettyWrapper$RouterChannelHandler.channelRead0(OAuth2HttpServer.kt:170)
        at no.nav.security.mock.oauth2.http.NettyWrapper$RouterChannelHandler.channelRead0(OAuth2HttpServer.kt:164)
        at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99)
[...]
`

I don't really understand the error message. A single response type should be fine from my understanding. It also works that way against our real authentication server (Keycloak). Any idea what I am doing wrong?

Edit: Just realized that implicit flow isn't listed as being supported in the Readme. If thats the case, is that something considered to be added anytime soon?

**Comment by tommytroen** [comment]
@geld0r Sorry for the late reply. Implicit flow is currently not supported as you mentioned. I'll have a look to see whats required to support it and get back to you.

**Comment by tommytroen** [comment]
Closing - ref: https://github.com/navikt/mock-oauth2-server/pull/148#issuecomment-995899482
